export async function GET(request: Request) {
    return new Response(JSON.stringify([
        {
            "__type": "CalendarTransport:http:\/\/jdlf.com.au\/ns\/data\/calendar",
            "activityId": 3521,
            "activityImportIdentifier": null,
            "activityType": 1,
            "allDay": false,
            "attendanceMode": 1,
            "attendeeUserId": 0,
            "backgroundColor": "#dce6f4",
            "calendarId": null,
            "categoryIds": null,
            "comment": null,
            "description": "",
            "eventSetupStatus": null,
            "finish": "2023-09-07T06:32:00Z",
            "guid": "2f85c0ff-61b2-455a-9abb-0df15147463a",
            "inClassStatus": null,
            "instanceId": "3521070920230534",
            "isRecurring": false,
            "learningTaskId": null,
            "lessonPlanConfigured": false,
            "location": null,
            "longTitle": "5:34: 9ENG12 - S1 - 2ENGSTAFF2",
            "longTitleWithoutTime": "9ENG12 - S1 - 2ENGSTAFF2",
            "managerId": 2899,
            "minutesMeetingId": null,
            "recurringFinish": null,
            "recurringStart": null,
            "repeatDays": null,
            "repeatForever": false,
            "repeatFrequency": 0,
            "repeatUntil": null,
            "rollMarked": false,
            "runningStatus": 1,
            "start": "2023-09-07T05:34:00Z",
            "targetStudentId": 3453,
            "teachingDaysOnly": false,
            "title": "9ENG12",
            "unavailablePd": null
        },
        {
            "__type": "CalendarTransport:http:\/\/jdlf.com.au\/ns\/data\/calendar",
            "activityId": 3535,
            "activityImportIdentifier": null,
            "activityType": 1,
            "allDay": false,
            "attendanceMode": 1,
            "attendeeUserId": 0,
            "backgroundColor": "#dce6f4",
            "calendarId": null,
            "categoryIds": null,
            "comment": null,
            "description": "",
            "eventSetupStatus": null,
            "finish": "2023-09-07T01:48:00Z",
            "guid": "d82e6b4b-9f3a-4eec-bf8c-ed1d39cdae76",
            "inClassStatus": null,
            "instanceId": "3535070920230050",
            "isRecurring": false,
            "learningTaskId": null,
            "lessonPlanConfigured": true,
            "location": null,
            "longTitle": "12:50: 9MATH13 - E1 - YCHO",
            "longTitleWithoutTime": "9MATH13 - E1 - YCHO",
            "managerId": 5447,
            "minutesMeetingId": null,
            "recurringFinish": null,
            "recurringStart": null,
            "repeatDays": null,
            "repeatForever": false,
            "repeatFrequency": 0,
            "repeatUntil": null,
            "rollMarked": false,
            "runningStatus": 1,
            "start": "2023-09-07T00:50:00Z",
            "targetStudentId": 3453,
            "teachingDaysOnly": false,
            "title": "9MATH13",
            "unavailablePd": null
        },
        {
            "__type": "CalendarTransport:http:\/\/jdlf.com.au\/ns\/data\/calendar",
            "activityId": 3549,
            "activityImportIdentifier": null,
            "activityType": 1,
            "allDay": false,
            "attendanceMode": 1,
            "attendeeUserId": 0,
            "backgroundColor": "#dce6f4",
            "calendarId": null,
            "categoryIds": null,
            "comment": null,
            "description": "",
            "eventSetupStatus": null,
            "finish": "2023-09-07T05:04:00Z",
            "guid": "88ebaf71-9ffb-4c1e-872b-40ce3d001360",
            "inClassStatus": null,
            "instanceId": "3549070920230406",
            "isRecurring": false,
            "learningTaskId": null,
            "lessonPlanConfigured": false,
            "location": null,
            "longTitle": "4:06: 9HASS14 - BL1 - KPYPER",
            "longTitleWithoutTime": "9HASS14 - BL1 - KPYPER",
            "managerId": 5450,
            "minutesMeetingId": null,
            "recurringFinish": null,
            "recurringStart": null,
            "repeatDays": null,
            "repeatForever": false,
            "repeatFrequency": 0,
            "repeatUntil": null,
            "rollMarked": false,
            "runningStatus": 1,
            "start": "2023-09-07T04:06:00Z",
            "targetStudentId": 3453,
            "teachingDaysOnly": false,
            "title": "9HASS14",
            "unavailablePd": null
        },
        {
            "__type": "CalendarTransport:http:\/\/jdlf.com.au\/ns\/data\/calendar",
            "activityId": 3674,
            "activityImportIdentifier": null,
            "activityType": 1,
            "allDay": false,
            "attendanceMode": 1,
            "attendeeUserId": 0,
            "backgroundColor": "#dce6f4",
            "calendarId": null,
            "categoryIds": null,
            "comment": null,
            "description": "",
            "eventSetupStatus": null,
            "finish": "2023-09-07T04:06:00Z",
            "guid": "3c235345-f909-4df2-86d0-e052063248dd",
            "inClassStatus": null,
            "instanceId": "3674070920230308",
            "isRecurring": false,
            "learningTaskId": null,
            "lessonPlanConfigured": false,
            "location": null,
            "longTitle": "3:08: 9SCI14 - AL1 - AMORTADZA",
            "longTitleWithoutTime": "9SCI14 - AL1 - AMORTADZA",
            "managerId": 2875,
            "minutesMeetingId": null,
            "recurringFinish": null,
            "recurringStart": null,
            "repeatDays": null,
            "repeatForever": false,
            "repeatFrequency": 0,
            "repeatUntil": null,
            "rollMarked": false,
            "runningStatus": 1,
            "start": "2023-09-07T03:08:00Z",
            "targetStudentId": 3453,
            "teachingDaysOnly": false,
            "title": "9SCI14",
            "unavailablePd": null
        },
        {
            "__type": "CalendarTransport:http:\/\/jdlf.com.au\/ns\/data\/calendar",
            "activityId": 3820,
            "activityImportIdentifier": null,
            "activityType": 1,
            "allDay": false,
            "attendanceMode": 1,
            "attendeeUserId": 0,
            "backgroundColor": "#dce6f4",
            "calendarId": null,
            "categoryIds": null,
            "comment": null,
            "description": "",
            "eventSetupStatus": null,
            "finish": "2023-09-07T02:46:00Z",
            "guid": "79960c55-e911-42d5-aa8d-a80d214f47a5",
            "inClassStatus": null,
            "instanceId": "3820070920230148",
            "isRecurring": false,
            "learningTaskId": null,
            "lessonPlanConfigured": false,
            "location": null,
            "longTitle": "1:48: 9TDTSC22 - MU7 - WWILSON",
            "longTitleWithoutTime": "9TDTSC22 - MU7 - WWILSON",
            "managerId": 2706,
            "minutesMeetingId": null,
            "recurringFinish": null,
            "recurringStart": null,
            "repeatDays": null,
            "repeatForever": false,
            "repeatFrequency": 0,
            "repeatUntil": null,
            "rollMarked": false,
            "runningStatus": 1,
            "start": "2023-09-07T01:48:00Z",
            "targetStudentId": 3453,
            "teachingDaysOnly": false,
            "title": "9TDTSC22",
            "unavailablePd": null
        },
        {
            "__type": "CalendarTransport:http:\/\/jdlf.com.au\/ns\/data\/calendar",
            "activityId": 4178,
            "activityImportIdentifier": null,
            "activityType": 1,
            "allDay": false,
            "attendanceMode": 1,
            "attendeeUserId": 0,
            "backgroundColor": "#dce6f4",
            "calendarId": null,
            "categoryIds": null,
            "comment": null,
            "description": "",
            "eventSetupStatus": null,
            "finish": "2023-09-07T07:30:00Z",
            "guid": "a447a3f8-28ea-4c74-a144-21e3f5db72c9",
            "inClassStatus": null,
            "instanceId": "4178070920230632",
            "isRecurring": false,
            "learningTaskId": null,
            "lessonPlanConfigured": false,
            "location": null,
            "longTitle": "6:32: 9TDTM21 - ML14 - HCHILLAPA",
            "longTitleWithoutTime": "9TDTM21 - ML14 - HCHILLAPA",
            "managerId": 5454,
            "minutesMeetingId": null,
            "recurringFinish": null,
            "recurringStart": null,
            "repeatDays": null,
            "repeatForever": false,
            "repeatFrequency": 0,
            "repeatUntil": null,
            "rollMarked": false,
            "runningStatus": 1,
            "start": "2023-09-07T06:32:00Z",
            "targetStudentId": 3453,
            "teachingDaysOnly": false,
            "title": "9TDTM21",
            "unavailablePd": null
        }
    ]));
}