export async function GET(request: Request) {
    try {
        return new Response(JSON.stringify([
            {
                "__type": "CalendarTransport:http:\/\/jdlf.com.au\/ns\/data\/calendar",
                "activityId": 3521,
                "activityImportIdentifier": null,
                "activityType": 1,
                "allDay": false,
                "attendanceMode": 1,
                "attendeeUserId": 0,
                "backgroundColor": "#dce6f4",
                "calendarId": null,
                "categoryIds": null,
                "comment": null,
                "description": "",
                "eventSetupStatus": null,
                "finish": "2023-09-05T04:06:00Z",
                "guid": "29edb8d2-8b92-48a9-9c93-ac00a253411c",
                "inClassStatus": null,
                "instanceId": "3521050920230308",
                "isRecurring": false,
                "learningTaskId": null,
                "lessonPlanConfigured": false,
                "location": null,
                "longTitle": "3:08: 9ENG12 - S1 - 2ENGSTAFF2",
                "longTitleWithoutTime": "9ENG12 - S1 - 2ENGSTAFF2",
                "managerId": 2899,
                "minutesMeetingId": null,
                "recurringFinish": null,
                "recurringStart": null,
                "repeatDays": null,
                "repeatForever": false,
                "repeatFrequency": 0,
                "repeatUntil": null,
                "rollMarked": true,
                "runningStatus": 1,
                "start": "2023-09-05T03:08:00Z",
                "targetStudentId": 3453,
                "teachingDaysOnly": false,
                "title": "9ENG12",
                "unavailablePd": null
            },
            {
                "__type": "CalendarTransport:http:\/\/jdlf.com.au\/ns\/data\/calendar",
                "activityId": 3535,
                "activityImportIdentifier": null,
                "activityType": 1,
                "allDay": false,
                "attendanceMode": 1,
                "attendeeUserId": 0,
                "backgroundColor": "#dce6f4",
                "calendarId": null,
                "categoryIds": null,
                "comment": null,
                "description": "",
                "eventSetupStatus": null,
                "finish": "2023-09-05T01:48:00Z",
                "guid": "50663081-5817-4093-a172-c51cba0892da",
                "inClassStatus": null,
                "instanceId": "3535050920230050",
                "isRecurring": false,
                "learningTaskId": null,
                "lessonPlanConfigured": true,
                "location": null,
                "longTitle": "12:50: 9MATH13 - E1 - YCHO",
                "longTitleWithoutTime": "9MATH13 - E1 - YCHO",
                "managerId": 5447,
                "minutesMeetingId": null,
                "recurringFinish": null,
                "recurringStart": null,
                "repeatDays": null,
                "repeatForever": false,
                "repeatFrequency": 0,
                "repeatUntil": null,
                "rollMarked": true,
                "runningStatus": 1,
                "start": "2023-09-05T00:50:00Z",
                "targetStudentId": 3453,
                "teachingDaysOnly": false,
                "title": "9MATH13",
                "unavailablePd": null
            },
            {
                "__type": "CalendarTransport:http:\/\/jdlf.com.au\/ns\/data\/calendar",
                "activityId": 3549,
                "activityImportIdentifier": null,
                "activityType": 1,
                "allDay": false,
                "attendanceMode": 1,
                "attendeeUserId": 0,
                "backgroundColor": "#dce6f4",
                "calendarId": null,
                "categoryIds": null,
                "comment": null,
                "description": "",
                "eventSetupStatus": null,
                "finish": "2023-09-05T06:32:00Z",
                "guid": "5af9c827-bd77-4e44-816b-bad7df082f0d",
                "inClassStatus": null,
                "instanceId": "3549050920230534",
                "isRecurring": false,
                "learningTaskId": null,
                "lessonPlanConfigured": false,
                "location": null,
                "longTitle": "5:34: 9HASS14 - BL1 - KPYPER",
                "longTitleWithoutTime": "9HASS14 - BL1 - KPYPER",
                "managerId": 5450,
                "minutesMeetingId": null,
                "recurringFinish": null,
                "recurringStart": null,
                "repeatDays": null,
                "repeatForever": false,
                "repeatFrequency": 0,
                "repeatUntil": null,
                "rollMarked": false,
                "runningStatus": 1,
                "start": "2023-09-05T05:34:00Z",
                "targetStudentId": 3453,
                "teachingDaysOnly": false,
                "title": "9HASS14",
                "unavailablePd": null
            },
            {
                "__type": "CalendarTransport:http:\/\/jdlf.com.au\/ns\/data\/calendar",
                "activityId": 3674,
                "activityImportIdentifier": null,
                "activityType": 1,
                "allDay": false,
                "attendanceMode": 1,
                "attendeeUserId": 0,
                "backgroundColor": "#dce6f4",
                "calendarId": null,
                "categoryIds": null,
                "comment": null,
                "description": "",
                "eventSetupStatus": null,
                "finish": "2023-09-05T02:46:00Z",
                "guid": "d69e1aea-880b-46dd-aaf6-3374aa2dd646",
                "inClassStatus": null,
                "instanceId": "3674050920230148",
                "isRecurring": false,
                "learningTaskId": null,
                "lessonPlanConfigured": false,
                "location": null,
                "longTitle": "1:48: 9SCI14 - AL1 - AMORTADZA",
                "longTitleWithoutTime": "9SCI14 - AL1 - AMORTADZA",
                "managerId": 2875,
                "minutesMeetingId": null,
                "recurringFinish": null,
                "recurringStart": null,
                "repeatDays": null,
                "repeatForever": false,
                "repeatFrequency": 0,
                "repeatUntil": null,
                "rollMarked": false,
                "runningStatus": 1,
                "start": "2023-09-05T01:48:00Z",
                "targetStudentId": 3453,
                "teachingDaysOnly": false,
                "title": "9SCI14",
                "unavailablePd": null
            },
            {
                "__type": "CalendarTransport:http:\/\/jdlf.com.au\/ns\/data\/calendar",
                "activityId": 3764,
                "activityImportIdentifier": null,
                "activityType": 1,
                "allDay": false,
                "attendanceMode": 1,
                "attendeeUserId": 0,
                "backgroundColor": "#dce6f4",
                "calendarId": null,
                "categoryIds": null,
                "comment": null,
                "description": "",
                "eventSetupStatus": null,
                "finish": "2023-09-05T05:04:00Z",
                "guid": "31313c6a-c490-441e-b681-98d1754c624a",
                "inClassStatus": null,
                "instanceId": "3764050920230406",
                "isRecurring": false,
                "learningTaskId": null,
                "lessonPlanConfigured": false,
                "location": null,
                "longTitle": "4:06: 9APDI22 - MU6 - GSTIMSON",
                "longTitleWithoutTime": "9APDI22 - MU6 - GSTIMSON",
                "managerId": 2960,
                "minutesMeetingId": null,
                "recurringFinish": null,
                "recurringStart": null,
                "repeatDays": null,
                "repeatForever": false,
                "repeatFrequency": 0,
                "repeatUntil": null,
                "rollMarked": true,
                "runningStatus": 1,
                "start": "2023-09-05T04:06:00Z",
                "targetStudentId": 3453,
                "teachingDaysOnly": false,
                "title": "9APDI22",
                "unavailablePd": null
            },
            {
                "__type": "CalendarTransport:http:\/\/jdlf.com.au\/ns\/data\/calendar",
                "activityId": 3816,
                "activityImportIdentifier": null,
                "activityType": 1,
                "allDay": false,
                "attendanceMode": 1,
                "attendeeUserId": 0,
                "backgroundColor": "#dce6f4",
                "calendarId": null,
                "categoryIds": null,
                "comment": null,
                "description": "",
                "eventSetupStatus": null,
                "finish": "2023-09-05T07:30:00Z",
                "guid": "ddc1f351-23d1-477b-afa1-e755dc8bafaa",
                "inClassStatus": null,
                "instanceId": "3816050920230632",
                "isRecurring": false,
                "learningTaskId": null,
                "lessonPlanConfigured": false,
                "location": null,
                "longTitle": "6:32: 9TELEC22 - G2 - HCHILLAPA",
                "longTitleWithoutTime": "9TELEC22 - G2 - HCHILLAPA",
                "managerId": 5454,
                "minutesMeetingId": null,
                "recurringFinish": null,
                "recurringStart": null,
                "repeatDays": null,
                "repeatForever": false,
                "repeatFrequency": 0,
                "repeatUntil": null,
                "rollMarked": false,
                "runningStatus": 1,
                "start": "2023-09-05T06:32:00Z",
                "targetStudentId": 3453,
                "teachingDaysOnly": false,
                "title": "9TELEC22",
                "unavailablePd": null
            }
        ]));
    } catch (e) {
        console.log(e);
        return new Response(e.message || e.toString(), { status: 500 });
    }
}