export async function GET(request: Request) {
    return new Response(JSON.stringify({
        "__type": "UserDetailsBlob",
        "chroniclePinnedCount": 0,
        "userACTStudentID": null,
        "userAccessRestrictions": null,
        "userCompassPersonId": "42532b63-52bf-469a-ac97-86f266822d79",
        "userDetails": "14 years, 2 months (25\/06\/09)",
        "userDisplayCode": "phodges",
        "userEmail": "paul.hodges@student.education.wa.edu.au",
        "userFirstName": "Paul",
        "userFlags": [],
        "userFormGroup": "09H",
        "userFullName": "Paul Hodges",
        "userGenderPronouns": null,
        "userHouse": "Sampson",
        "userId": 3453,
        "userLastName": "Hodges",
        "userPhoneExtension": null,
        "userPhotoPath": "\/download\/cdn\/full\/2fde3c3f-5545-4463-8c38-1ff51f38785b_0806230214AM.jpg",
        "userPreferredLastName": "",
        "userPreferredName": "Paul",
        "userRole": 1,
        "userRoleInSchool": null,
        "userSchoolId": "perthmodern.wa.edu.au",
        "userSchoolURL": "perthmodern-wa.compass.education",
        "userSquarePhotoPath": "\/download\/cdn\/square\/2fde3c3f-5545-4463-8c38-1ff51f38785b_0806230214AM.jpg",
        "userStatus": 1,
        "userSussiID": "PAUL.HODGES",
        "userTimeLinePeriods": [
            {
                "__type": "TimelinePeriod:http:\/\/jdlf.com.au\/ns\/data\/attendance\/v2",
                "attendanceOverride": true,
                "exportId": "",
                "extendedStatus": null,
                "finish": "2023-09-06T00:48:00Z",
                "name": "Period 0 (BS)",
                "onCampus": true,
                "start": "2023-09-05T23:50:00Z",
                "status": null,
                "statusName": "",
                "teachingTime": true,
                "userId": 3453
            },
            {
                "__type": "TimelinePeriod:http:\/\/jdlf.com.au\/ns\/data\/attendance\/v2",
                "attendanceOverride": true,
                "exportId": "\/",
                "extendedStatus": {
                    "__type": "Es:http:\/\/jdlf.com.au\/ns\/business\/attendance\/transport",
                    "attendanceGridDisplayMode": null,
                    "attendanceGridOrdinal": null,
                    "c": "Code: \/",
                    "d": "Student is considered to be attending a normal curriculum class (WA DoE 'Present In Class' Status)",
                    "def": false,
                    "eventsUi": true,
                    "id": 480,
                    "isAttendanceAdminDefault": false,
                    "isCustom": false,
                    "lastModified": null,
                    "lastModifiedUserId": null,
                    "n": "Present",
                    "note": "",
                    "parentApprovalsUi": false,
                    "pdef": false,
                    "periodCalc_LateParentApproved": false,
                    "periodCalc_LateUnapproved": false,
                    "periodCalc_NotMarked": false,
                    "periodCalc_NotPresentUnapproved": false,
                    "periodCalc_Present": true,
                    "rowGuid": "00000000-0000-0000-0000-000000000000",
                    "schoolActivitiesUi": false,
                    "schoolSystemCountedAbsence": false,
                    "schoolSystemExportIdentifier": "\/",
                    "schoolSystemType": 4,
                    "shortName": "Present",
                    "sourceRowGuid": null,
                    "standardClassesUi": true,
                    "studentApprovalsUi": false,
                    "uiStatus": 1
                },
                "finish": "2023-09-06T01:48:00Z",
                "name": "Period 1",
                "onCampus": true,
                "start": "2023-09-06T00:50:00Z",
                "status": 1,
                "statusName": "Present",
                "teachingTime": true,
                "userId": 3453
            },
            {
                "__type": "TimelinePeriod:http:\/\/jdlf.com.au\/ns\/data\/attendance\/v2",
                "attendanceOverride": true,
                "exportId": "\/",
                "extendedStatus": {
                    "__type": "Es:http:\/\/jdlf.com.au\/ns\/business\/attendance\/transport",
                    "attendanceGridDisplayMode": null,
                    "attendanceGridOrdinal": null,
                    "c": "Code: \/",
                    "d": "Student is considered to be attending a normal curriculum class (WA DoE 'Present In Class' Status)",
                    "def": false,
                    "eventsUi": true,
                    "id": 480,
                    "isAttendanceAdminDefault": false,
                    "isCustom": false,
                    "lastModified": null,
                    "lastModifiedUserId": null,
                    "n": "Present",
                    "note": "",
                    "parentApprovalsUi": false,
                    "pdef": false,
                    "periodCalc_LateParentApproved": false,
                    "periodCalc_LateUnapproved": false,
                    "periodCalc_NotMarked": false,
                    "periodCalc_NotPresentUnapproved": false,
                    "periodCalc_Present": true,
                    "rowGuid": "00000000-0000-0000-0000-000000000000",
                    "schoolActivitiesUi": false,
                    "schoolSystemCountedAbsence": false,
                    "schoolSystemExportIdentifier": "\/",
                    "schoolSystemType": 4,
                    "shortName": "Present",
                    "sourceRowGuid": null,
                    "standardClassesUi": true,
                    "studentApprovalsUi": false,
                    "uiStatus": 1
                },
                "finish": "2023-09-06T02:46:00Z",
                "name": "Period 2",
                "onCampus": true,
                "start": "2023-09-06T01:48:00Z",
                "status": 1,
                "statusName": "Present",
                "teachingTime": true,
                "userId": 3453
            },
            {
                "__type": "TimelinePeriod:http:\/\/jdlf.com.au\/ns\/data\/attendance\/v2",
                "attendanceOverride": true,
                "exportId": "\/",
                "extendedStatus": {
                    "__type": "Es:http:\/\/jdlf.com.au\/ns\/business\/attendance\/transport",
                    "attendanceGridDisplayMode": null,
                    "attendanceGridOrdinal": null,
                    "c": "Code: \/",
                    "d": "Student is considered to be attending a normal curriculum class (WA DoE 'Present In Class' Status)",
                    "def": false,
                    "eventsUi": true,
                    "id": 480,
                    "isAttendanceAdminDefault": false,
                    "isCustom": false,
                    "lastModified": null,
                    "lastModifiedUserId": null,
                    "n": "Present",
                    "note": "",
                    "parentApprovalsUi": false,
                    "pdef": false,
                    "periodCalc_LateParentApproved": false,
                    "periodCalc_LateUnapproved": false,
                    "periodCalc_NotMarked": false,
                    "periodCalc_NotPresentUnapproved": false,
                    "periodCalc_Present": true,
                    "rowGuid": "00000000-0000-0000-0000-000000000000",
                    "schoolActivitiesUi": false,
                    "schoolSystemCountedAbsence": false,
                    "schoolSystemExportIdentifier": "\/",
                    "schoolSystemType": 4,
                    "shortName": "Present",
                    "sourceRowGuid": null,
                    "standardClassesUi": true,
                    "studentApprovalsUi": false,
                    "uiStatus": 1
                },
                "finish": "2023-09-06T04:06:00Z",
                "name": "Period 3",
                "onCampus": true,
                "start": "2023-09-06T03:08:00Z",
                "status": 1,
                "statusName": "Present",
                "teachingTime": true,
                "userId": 3453
            },
            {
                "__type": "TimelinePeriod:http:\/\/jdlf.com.au\/ns\/data\/attendance\/v2",
                "attendanceOverride": true,
                "exportId": "\/",
                "extendedStatus": {
                    "__type": "Es:http:\/\/jdlf.com.au\/ns\/business\/attendance\/transport",
                    "attendanceGridDisplayMode": null,
                    "attendanceGridOrdinal": null,
                    "c": "Code: \/",
                    "d": "Student is considered to be attending a normal curriculum class (WA DoE 'Present In Class' Status)",
                    "def": false,
                    "eventsUi": true,
                    "id": 480,
                    "isAttendanceAdminDefault": false,
                    "isCustom": false,
                    "lastModified": null,
                    "lastModifiedUserId": null,
                    "n": "Present",
                    "note": "",
                    "parentApprovalsUi": false,
                    "pdef": false,
                    "periodCalc_LateParentApproved": false,
                    "periodCalc_LateUnapproved": false,
                    "periodCalc_NotMarked": false,
                    "periodCalc_NotPresentUnapproved": false,
                    "periodCalc_Present": true,
                    "rowGuid": "00000000-0000-0000-0000-000000000000",
                    "schoolActivitiesUi": false,
                    "schoolSystemCountedAbsence": false,
                    "schoolSystemExportIdentifier": "\/",
                    "schoolSystemType": 4,
                    "shortName": "Present",
                    "sourceRowGuid": null,
                    "standardClassesUi": true,
                    "studentApprovalsUi": false,
                    "uiStatus": 1
                },
                "finish": "2023-09-06T05:04:00Z",
                "name": "Period 4",
                "onCampus": true,
                "start": "2023-09-06T04:06:00Z",
                "status": 1,
                "statusName": "Present",
                "teachingTime": true,
                "userId": 3453
            },
            {
                "__type": "TimelinePeriod:http:\/\/jdlf.com.au\/ns\/data\/attendance\/v2",
                "attendanceOverride": true,
                "exportId": "\/",
                "extendedStatus": {
                    "__type": "Es:http:\/\/jdlf.com.au\/ns\/business\/attendance\/transport",
                    "attendanceGridDisplayMode": null,
                    "attendanceGridOrdinal": null,
                    "c": "Code: \/",
                    "d": "Student is considered to be attending a normal curriculum class (WA DoE 'Present In Class' Status)",
                    "def": false,
                    "eventsUi": true,
                    "id": 480,
                    "isAttendanceAdminDefault": false,
                    "isCustom": false,
                    "lastModified": null,
                    "lastModifiedUserId": null,
                    "n": "Present",
                    "note": "",
                    "parentApprovalsUi": false,
                    "pdef": false,
                    "periodCalc_LateParentApproved": false,
                    "periodCalc_LateUnapproved": false,
                    "periodCalc_NotMarked": false,
                    "periodCalc_NotPresentUnapproved": false,
                    "periodCalc_Present": true,
                    "rowGuid": "00000000-0000-0000-0000-000000000000",
                    "schoolActivitiesUi": false,
                    "schoolSystemCountedAbsence": false,
                    "schoolSystemExportIdentifier": "\/",
                    "schoolSystemType": 4,
                    "shortName": "Present",
                    "sourceRowGuid": null,
                    "standardClassesUi": true,
                    "studentApprovalsUi": false,
                    "uiStatus": 1
                },
                "finish": "2023-09-06T06:32:00Z",
                "name": "Period 5",
                "onCampus": true,
                "start": "2023-09-06T05:34:00Z",
                "status": 1,
                "statusName": "Present",
                "teachingTime": true,
                "userId": 3453
            },
            {
                "__type": "TimelinePeriod:http:\/\/jdlf.com.au\/ns\/data\/attendance\/v2",
                "attendanceOverride": true,
                "exportId": "",
                "extendedStatus": null,
                "finish": "2023-09-06T07:30:00Z",
                "name": "Period 6 (AS)",
                "onCampus": true,
                "start": "2023-09-06T06:32:00Z",
                "status": null,
                "statusName": "",
                "teachingTime": true,
                "userId": 3453
            },
            {
                "__type": "TimelinePeriod:http:\/\/jdlf.com.au\/ns\/data\/attendance\/v2",
                "attendanceOverride": true,
                "exportId": "",
                "extendedStatus": null,
                "finish": "2023-09-06T08:30:00Z",
                "name": "Period 7 (AS)",
                "onCampus": true,
                "start": "2023-09-06T07:32:00Z",
                "status": null,
                "statusName": "",
                "teachingTime": true,
                "userId": 3453
            }
        ],
        "userVSN": null,
        "userYearLevel": "Year 9",
        "userYearLevelId": 9
    }));
}